
export const metadata = {
  title: 'Инструкции',
  description: 'Generated by create next app',
}

export default function Layout({children}) {
  return (
    <>
      { children }  
    </>    
  )
}