version: '3.9'
services:
  nextjs:
    container_name: nextjs
    build: ./myline-next
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g "daemon off;"
    
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot/ --email ferrdevil220@gmail.com  -d myline.clinic -d www.myline.clinic --agree-tos
 
