version: '3.9'
services:
  nextjs:
    build: ./myline-next
    ports:
      - "3000:3000"
    networks:
      - docker-network
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    networks:
      - docker-network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
networks:
  docker-network:
    driver: bridge