version: '3.9'
services:
  nextjs:
    build: ./myline-next
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
