version: '3.9'
services:
  nextjs:
    container_name: nextjs
    build: ./myline-next
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g "daemon off;"
 
