version: '3.9'
services:
  nextjs:
    container_name: 'nextjs'
    build: ./myline-next
    ports:
      - 80:3000
    networks:
      - docker-network
  nginx:
    container_name: 'nginx'
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"

    networks:
      - docker-network
 
networks:
  docker-network:
    driver: bridge