version: '3.9'
services:
  nextjs:
    build: ./myline-next
    ports:
      - "3000:3000"
    networks:
      - docker-network
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge