import ProfileLayout from "@/services/profile/components/ProfileLayout/ProfileLayout"

export const metadata = {
  title: 'Прием',
  description: 'Generated by create next app',
}

export default function Layout({children}) {
  return (
    <>
      { children } 
    </>
  )
}