import DocumentsLayout from "./components/DocumentsLayout/DocumentsLayout"

export const metadata = {
  title: 'Документационные материалы',
  description: 'Generated by create next app',
}

export default function Layout({children}) {
  return (
    <DocumentsLayout>
      { children }  
    </DocumentsLayout>    
  )
}