export const metadata = {
  title: 'Публикации в СМИ',
  description: 'Generated by create next app',
}

export default function Layout(ctx) {
  return (
    <>
      {ctx.children}  
    </>    
  )
}