export const metadata = {
  title: 'Политика конфиденциальности',
  description: 'Generated by create next app',
}

export default function Layout({children}) {
  return (
    <>
      { children } 
    </>
  )
}